### PR TITLE
replace last jquery with plain browser api

### LINKED ISSUE #2217: Questionnaire reordering fails
When reordering questionnaires on the questionnaire index page, a `403` error is returned. This happens because the CSRF token is missing: `Forbidden (CSRF token missing.): /staff/questionnaire/update_indices`

### PR DESCRIPTION
**Pull request by Kakadus**
close #2217

### CODE REVIEW

**Comment by niklasmohrin** [comment]
Huh? Wouldn't the real fix be to replace the `$.post` call with a `fetch`? Or does this occur in more places? As far as I can tell, sortablejs does not use jquery itself and it should be all our doing

**Review by richardebeling — APPROVED** [review]

File: evap/static/ts/src/datagrid.ts [hunk 1]
```diff
@@ -341,11 +343,19 @@ export class QuestionnaireGrid extends TableGrid {
             draggable: ".sortable",
             scrollSensitivity: 70,
             onUpdate: event => {
-                if (event.oldIndex && event.newIndex) {
+                if (event.oldIndex !== undefined && event.newIndex !== undefined) {
```
Comment (Kakadus) [inline evap/static/ts/src/datagrid.ts:346]: since migration to typescript: if indices were 0, this did not work

**Review by janno42 — APPROVED** [review]
✅ UI works

Thanks for fixing the bug with ordering the first item as well 🎆

**Review by richardebeling — APPROVED** [review]
